name: Daft Labs
favicon: null
layout_spectrum: 0.7230521093588322
typography_spectrum: 0.5524015622213483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.33420838881284
  lightness: 0.21611833688803017
  saturation: 0.7269153888337314
  rhythmicContrast: 0.6132965332362801
purpose: []
